[package]
name = "photoframe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
serde_json = "1.0"
sha1 = "0.10"
tokio = { version = "1.32", features = ["full"] }